import type { PerfilChecklist } from '@ambientalia/shared'

/**
 * Catálogo inicial del checklist "Incluye" de las remisiones de ENTRADA, extraído de los nodos de
 * formulario del flujo n8n `Remisiones_ST_3.13_Desk` (export del 2026-08-03).
 *
 * Solo se usa para la SIEMBRA puntual vía `POST /api/admin/seed-remision-checklist`. A partir de ahí
 * manda la tabla `public.remision_checklist`: nada vuelve a leer este fichero, para no repetir lo que
 * pasaba con la semilla CSV de equipos (editabas la tabla y el arranque revertía tus cambios).
 *
 * Los textos vienen normalizados (espacios dobles colapsados y extremos recortados): el original traía
 * varios con espacio final, que habrían envenenado el cruce con la rama de salida.
 *
 * `kunak` no aparece a propósito: su formulario nunca tuvo checklist.
 */
export const CHECKLIST_SEED: Partial<Record<PerfilChecklist, string[]>> = {
  grimm_edm280: [
    "Adaptador de voltaje 12V DC",
    "Cabezal de muestra",
    "Cabezal TSP",
    "Cable de poder",
    "Cable meteorologia",
    "Cable RJ45",
    "Cable RS232",
    "Cable RS232 + conversor USB-RS232",
    "Cable USB",
    "Caja de transporte",
    "Datalogger",
    "Documentación de calibración",
    "Kit montaje (pletinas + tornillos)",
    "Manuales",
    "Memoria USB",
    "Pletinas (par)",
    "Repuestos reemplazados",
    "Sensor Meteorológico 157L",
    "Sensor Meteorológico 158L",
    "Sensor Meteorológico 158L + accesorios",
    "Sensor Meteorológico 159L",
    "Sensor Meteorológico 159L + accesorios",
    "Trampa de agua",
    "Trampa de agua + manguera",
    "Tubo de muestreo 1,5 m",
    "Tubo de muestreo 1,5 m + Cable Met.",
  ],
  grimm_edm180: [
    "Adaptador de voltaje 12V DC",
    "Cabezal de muestra",
    "Cabezal TSP",
    "Cable 158-EE 3,5 m",
    "Cable de poder",
    "Cable RJ45",
    "Cable RS232",
    "Cable RS232 + conversor USB-RS232",
    "Caja de transporte",
    "Datalogger",
    "Documentación de calibración",
    "Escudo de radiación para 1158-TRH",
    "Kit montaje (pletinas + tornillos)",
    "Manuales",
    "Pletinas (par)",
    "Repuestos reemplazados",
    "Sensor 1158-TRH",
    "Sensor 158-TRH + escudo radiación",
    "Sensor Meteorológico 159L",
    "Sensor Meteorológico 159L + accesorios",
    "Tarjeta PCMCIA",
    "Trampa de agua",
    "Trampa de agua + manguera",
    "Tubo de muestreo 1,5 m",
    "Tubo de muestreo 1,5 m + Cable 1158-EE 3,5 m",
  ],
  horiba_ap: [
    "Brackets",
    "Cable de poder",
    "Cable RS232",
    "Cable RS232 + conversor USB-RS232",
    "Caja de transporte",
    "Cap Nut",
    "Documentación de calibración",
    "Filtro de partículas",
    "Manuales",
    "Memoria USB",
    "Repuestos reemplazados",
    "Sleeves",
    "Slides",
    "Tarjeta Compact Flash",
    "Tuberia de teflón",
  ],
  environics: [
    "Cable de poder",
    "Cable RS232",
    "Cable RS232 + conversor USB-RS232",
    "Caja de transporte",
    "Conexión en T",
    "Filtro de partículas",
    "Manuales",
    "Memoria USB",
    "Racor + ferula en acero",
    "Racor + ferula en bronce",
    "Racor + ferula en plástico o teflón",
    "Racor en acero",
    "Racor en bronce",
    "Racor en plastico o teflón",
    "Repuestos reemplazados",
    "Tuberia de teflón",
  ],
  otro: [
    "Adaptador de voltaje 12V DC",
    "Aire acondicionado",
    "Baterias",
    "Blower",
    "Cable de poder",
    "Cable meteorologia",
    "Cable RJ45",
    "Cable RS232",
    "Cable RS232 + conversor USB-RS232",
    "Cable USB",
    "Caja de transporte",
    "Capuchón de acero",
    "Carbón activado",
    "Extensión de alimentación",
    "Filtro para carbono",
    "Filtro teflón",
    "Gabinete",
    "Maletín de transporte",
    "Manuales",
    "Repuestos reemplazados",
    "S 316",
    "Sistema de muestreo en acero",
    "Soluciones referencia de PH",
    "Soluciones referencia de conductividad",
    "SR-305",
    "Tuberia en teflón",
    "UPS",
  ],
}
